version: 2

sources:
  - name: example_db
    schema: main  
    tables:
      - name: orders 
      - name: users

models:
  - name: view_users
    description: calculated incremental model of user status
    columns:
      - name: user_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: registration_date
        tests:
          - not_null
      - name: order_count
        tests:
          - not_null
      - name: total_purchase_amount
        tests:
          - not_null
      - name: avg_purchase_amount
        tests:
          - not_null
      - name: last_order_date
      - name: actual_status
        tests:
          - not_null